# ============================================================================
# MASTER STATE
# ============================================================================

from dataclasses import dataclass, field
from datetime import datetime
from typing import Tuple, Optional, List, Literal
from typing_extensions import TypedDict
from pydantic import BaseModel, Field

@dataclass
class MasterState:
    # === INPUT MESSAGE ===
    message: str = ""
    route: str = ""
    user_response: str = "" # Landing field for Human-in-the-Loop responses
    response: str = ""  # Rich markdown response to stream back to the UI (set by workflow finalizers)
    reset_profile: bool = False # Flag for total Long-Term Memory wipe

    
    # === CONFIGURAZIONE (riempiti da route_request) ===
    st_email: str = ""
    st_password: str = ""
    base_dir: str = ""
    cubemx_path: str = ""
    
    # === WEB RESEARCH ===
    search_type: str = ""
    search_query: str = ""
    search_results: str = ""
    search_results_list: List[str] = field(default_factory=list) # List of individual results for DeepEval
    search_summary: str = "" # Summary generated by LLM
    web_research_success: bool = False
    
    # === WORKFLOW 1: STM32 FIRMWARE GENERATION ===
    ioc_file_path: Optional[str] = None
    board_name: Optional[str] = None
    mcu_series: Optional[str] = None
    project_name: Optional[str] = None
    toolchain: Optional[str] = None
    
    # Package Installation
    package_installation_success: bool = False
    package_error_message: Optional[str] = None
    
    firmware_script_path: str = ""
    firmware_project_path: str = ""
    firmware_script_content: str = ""
    firmware_generation_success: bool = False
    firmware_error_message: Optional[str] = None
    
    # === WORKFLOW 2: AI ANALYSIS ===
    model_path: str = ""
    target: str = "stm32f401"
    ai_output_dir: str = ""
    compression: str = "high"
    
    analyze_report_dir: str = ""
    validate_report: str = ""
    generate_code_dir: str = ""
    
    analyze_success: bool = False
    validate_success: bool = False
    generate_success: bool = False
    ai_error_message: Optional[str] = None

    # Resource Checks
    ram_usage: int = 0
    flash_usage: int = 0
    resource_check_result: str = "ok" # "ok", "warning", "critical", "error", "retry"
    needs_compression_retry: bool = False  # Flag for auto-retry with higher compression

    # === DISCOVERY FIELDS ===
    model_discovery_method: str = ""  # "default", "taskbased", "recommendation", "search"
    available_models: List[dict] = field(default_factory=list)  # Suggested models
    selected_model: Optional[dict] = None  # Chosen model
    search_iterations: int = 0  # Online search counter (max 3)
    model_accepted: bool = False  # Has user accepted the model?
    last_task: str = ""  # image_classification, object_detection, human_activity_recognition
    custom_use_case: str = ""  # New: specific user use case
    is_new_registration: bool = False  # True if it's a newly registered model by the user
    pending_model_entry: Optional[dict] = None  # Model data pending technical validation

    # === WORKFLOW 3: INTEGRATION ===
    ai_code_dir: str = ""
    firmware_project_dir: str = ""
    network_name: str = "network"
    modify_main: bool = True
    
    ai_src_files: List[str] = field(default_factory=list)
    ai_header_files: List[str] = field(default_factory=list)
    firmware_src_dir: str = ""
    firmware_inc_dir: str = ""
    main_c_path: str = ""
    
    copy_success: bool = False
    scan_success: bool = False
    main_modification_success: bool = False
    integration_success: bool = False
    integration_error_message: Optional[str] = None

    # === WORKFLOW 5: MODEL CUSTOMIZATION ===
    # Architecture inspection
    model_architecture: dict = field(default_factory=dict)  # Input/output shapes, n_layers, etc.
    model_summary_text: str = ""  # Full text of model.summary()

    wants_model_modifications: bool = False  
    modification_intent_confidence: float = 0.0  
    
    # Best practices
    best_practices_display: str = ""  # Formatted best practices for the user
    best_practices_raw: List[str] = field(default_factory=list)  # Raw best practices docs
    
    # User customization request
    user_custom_modifications: str = ""  # Unconstrained user prompt
    
    # Parsed modifications
    parsed_modifications: Optional[dict] = None  # Structured modifications from LLM
    modification_confirmed: bool = False  # Has user confirmed the modifications?
    user_wants_to_edit: bool = False  # Does user want to edit the customization request?
    
    # Applied customization
    customized_model_path: str = ""  # Path of the customized model (.h5)
    customization_applied: bool = False  # Flag if modifications have been applied
    customized_model_info: dict = field(default_factory=dict)  # Info after customization
    
    # Training validation
    training_test_result: dict = field(default_factory=dict)  # Training test results
    training_validation_success: bool = False
    
    # Final model
    final_model_path: str = ""  # Path to the finalized saved customized model

    # Environment management
    python_path: str = ""  # Path del Python interpreter (es: /usr/bin/python)
    conda_env: str = ""    # Nome ambiente conda (es: 'stm32legacy', 'stm32')
    
    # Decision after customization
    continue_after_customization: bool = False  # Continua con AI analysis?
    
    # Training parameters
    custom_learning_rate: float = 0.0001  # Learning rate per fine-tuning (start with 1e-4)
    custom_epochs: int = 10  # Epoche di training
    custom_batch_size: int = 64  # Batch size (più grande = più veloce, più memoria)
    
    # Quantization (per STM32)
    should_quantize: bool = False  # Quantizzare per embedded?
    quantization_bit_width: int = 8  # INT8, INT16, etc.
    quantized_model_path: str = ""  # Path to quantized model (.tflite)

    # === COMMON ===
    timestamp: str = field(default_factory=lambda: datetime.now().strftime("%Y%m%d_%H%M%S"))

    # === WORKFLOW 6: SYNTHETIC DATA ===
    synthetic_request: dict = field(default_factory=dict)  # Request parameters
    synthetic_data_path: str = ""  # Path output
    synthetic_files_count: int = 0  # Numero file generati
    use_synthetic_data: bool = False  # Flag se usare dati sintetici

    # === WORKFLOW 7: DATASET SELECTION ===
    dataset_source: str = ""  # "real", "synthetic", "both"
    real_dataset_name: str = ""  # es. "cifar10", "esc50"
    real_dataset_path: str = ""  # Path locale del dataset scaricato
    
    # === NNI OPTIMIZATION ===
    optimization_mode: str = "standard"  # "nni", "standard" - modalità di ottimizzazione iperparametri

    # === CROSS-SESSION CONTEXT ===
    persistent_context: dict = field(default_factory=dict) # Persistent user info (e.g. preferred board)

# ============================================================================
# INPUT SCHEMA
# ============================================================================

class MasterInput(TypedDict, total=False):
    message: str
    user_response: str
    persistent_context: dict

# The server.py file successfully loaded the user profile, but this state.py file had a restrictive definition of "Input" that silently filtered and discarded that profile before it entered the graph.
# Di conseguenza, l'LLM partiva sempre "da zero".
