name: "nomic-embed"
backend: "python"
max_batch_size: 8

input [
  {
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "EMBEDDING"
    data_type: TYPE_FP32
    dims: [ 768 ]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]
